# Generated by Django 4.2.1 on 2023-06-06 21:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.CharField(default='ALBUM', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(default='GENRE', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='year',
            field=models.IntegerField(default=1990),
            preserve_default=False,
        ),
    ]
