# Generated by Django 4.2.1 on 2023-06-06 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_artist_song_album_song_created_at_song_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='songs.artist'),
            preserve_default=False,
        ),
    ]
