# Generated by Django 4.2.1 on 2023-06-27 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_alter_song_options_alter_song_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
